---
core:
    num_workers: 2
inventory: 
    plugin: nornir.plugins.inventory.simple.SimpleInventory
options:
    host_file: "inventory/RouterIntel/hosts.yaml"
    group_file: "inventory/RouterIntel/groups.yaml"
    defaults_file: "inventory/RouterIntel/defaults.yaml"