R1:
  hostname: 192.168.122.197
  groups:
  data:
    site: Guildford
    tags:
      - 3725
R2:
  hostname: 192.168.122.92
  groups:
  data:
    tags:
      - 3725
R3:
  hostname: 192.168.122.130
  groups:
  data:
    tags:
      - 3725
